server:
  port: 8080

spring:
  application:
    name: ${SERVICE_NAME}
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: ${ZIPKIN_ENDPOINT}

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_ENDPOINT}