server:
  port: 8080

spring:
  application:
    name: ${SERVICE_NAME}
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
    base-url: ${ZIPKIN_ENDPOINT}


eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_ENDPOINT}